apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: kubeless_function_name
  namespace: default
  label:
    created-by: kubeless
    function: kubeless_function_name
spec:
  checksum: CHECKSUM_SHA256
  runtime: kubeless_function_runtime
  deployment:
    spec:
      selector: null
      template:
        spec:
          containers:
            - env:
                - name: FOO
                  value: bar
              imagePullPolicy: Always
              name: ""
              resources:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
  timeout: "180"
  handler: kubeless_function_handler_filename.node_function_name
  deps: DEPENDENCIES
  function: FUNCTION_BASE64
  function-content-type: base64+zip
  service:
    ports:
      - name: http-function-port
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      created-by: kubeless
      function: kubeless_function_name
    type: ClusterIP
